# Create a lxd container on the current host.
# Populate local /etc/hosts file and and ansible inventory with # hostname and ip address information.
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Create a started lxd container with a user for ansible
      community.general.lxd_container:
        name: lxd-container-00
        state: started
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams
          alias: focal
        config:
          user.user-data: |
            #cloud-config
            users:
            - name: ansible
              gecos: Ansible User
              groups: users, admin, wheel
              sudo: ALL=(ALL) NOPASSWD:ALL
              shell: /bin/bash
              lock_passwd: true
              ssh_authorized_keys:
                - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRCJCQ1UD9QslWDSw5Pwsvba0Wsf1pO4how5BtNaZn0xLZpTq2nqFEJshUkd/zCWF7DWyhmNphQ8c+U+wcmdNVcg2pI1kPxq0VZzBfZ7cDwhjgeLsIvTXvU+HVRtsXh4c5FlUXpRjf/x+a3vqFRvNsRd1DE+5ZqQHbOVbnsStk3PZppaByMg+AZZMx56OUk2pZCgvpCwj6LIixqwuxNKPxmJf45RyOsPUXwCwkq9UD4me5jksTPPkt3oeUWw1ZSSF8F/141moWsGxSnd5NxCbPUWGoRfYcHc865E70nN4WrZkM7RFI/s5mvQtuj8dRL67JUEwvdvEDO0EBz21FV/iOracXd2omlTUSK+wYrWGtiwQwEgr4r5bimxDKy9L8UlaJZ+ONhLTP8ecTHYkaU1C75sLX9ZYd5YtqjiNGsNF+wdW6WrXrQiWeyrGK7ZwbA7lagSxIa7yeqnKDjdkcJvQXCYGLM9AMBKWeJaOpwqZ+dOunMDLd5VZrDCU2lpCSJ1M="
      register: addresses

    - name: Print container address for debugging
      debug:
           var: addresses.addresses.eth0

    - name: Add lxd-container-00 to /etc/hosts file
      become: yes
      lineinfile:
        path: /etc/hosts
        insertafter: EOF
        line: "{{addresses.addresses.eth0[0]}} lxd-container-00"

    - name: Create a new ansible inventory file (yaml format) at [{{playbook_dir}}]
      copy:
        dest: "{{playbook_dir}}/new_ansible_hosts"
        content: |
          all:
            hosts:
              lxd-container-00
